[package]

name = "grust-proof"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"

[dependencies.grust]
git = "https://github.com/gi-rust/grust.git"
branch = "stable"

[dependencies.grust-gio-2-0]
path = "fake-gen/gio"
